### ISSUE TITLE
对论文中的实验结果存在疑问

### ISSUE THREAD

**Issue by ethan-phu** [FlamingJay/Time-related-Intrusion-Detection-Model-based-on-Recurrent-Neural-Network#2]
[实验结果](https://tva1.sinaimg.cn/large/007S8ZIlgy1gf7tc5j93ej30eq0jzwgv.jpg)
您好，我复现了您的实验，使用的是和论文中同样的参数，结果却并没有您论文中所提及的效果。请问是怎么回事呢？

**Comment by FlamingJay** [comment]
您好，结果相差很多么？目前，代码中的参数并不是最优的。

**Comment by ethan-phu** [comment]
相差的有点大！我这边再尝试跑一次吧！这个工作我是很久以前做的了。之后我把跑的结果截图给您

**Comment by xzhatgeek** [comment]
本人复现结果第一次为97.8%，第二次将分类器替换为GRU后为98.12% 继续几次还是有点波动不过基本接近宣称的超过98%，不过这个好像不适用于多分类。

**Comment by FlamingJay** [comment]
好的，多分类的话可能需要转换成其他策略了，值得一试。
祝科研顺利。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FlamingJay/Time-related-Intrusion-Detection-Model-based-on-Recurrent-Neural-Network"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月6日(星期五) 晚上9:36
收件人:&nbsp;"FlamingJay/Time-related-Intrusion-Detection-Model-based-on-Recurrent-Neural-Network"<Time-related-Intrusion-Detection-Model-based-on-Recurrent-Neural-Network@noreply.github.com&gt;;
抄送:&nbsp;"王杰"<601275571@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [FlamingJay/Time-related-Intrusion-Detection-Model-based-on-Recurrent-Neural-Network] 对论文中的实验结果存在疑问 (#2)





 
本人复现结果第一次为97.8%，第二次将分类器替换为GRU后为98.12% 继续几次还是有点波动不过基本接近宣称的超过98%，不过这个好像不适用于多分类。
