### ISSUE TITLE
There is no file called 'saved_models_temp/best_model.hdf5' created after running data_generator.py

### ISSUE THREAD

**Issue by muse-coder** [FlamingJay/Time-related-Intrusion-Detection-Model-based-on-Recurrent-Neural-Network#4]
I cann't totally run this code, because in line 93 ,it does not create new checkpoint, then it occurred error in line 98,99. what's wrong?

**Comment by hefeifei13** [comment]
我也是啊，找不saved_models_temp/best_model.hdf5文件

**Comment by hefeifei13** [comment]
老哥是咋麽處理的

**Comment by hefeifei13** [comment]
> 我不能完全运行这段代码，因为在第 93 行，它没有创建新的检查点，然后在第 98,99 行发生错误。怎么了？

我也是啊，找不saved_models_temp/best_model.hdf5文件
